### ISSUE TITLE
Create social accounts

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-website#12]
Folks like following official twitter accounts for regular updates

**Comment by bhackett1024** [comment]
I created a twitter account @WebReplay1.  Both WebReplay and Web_Replay are existing accounts that haven't been touched in 7 years but it doesn't look like there is any mechanism to release those handles.  Would another user name be preferable?

**Comment by bhackett1024** [comment]
I've added links to the twitter and facebook accounts on the contact page
