### ISSUE TITLE
Website tweaks

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-website#15]
1. when I’m resizing the window the text in the header can but right up against the right side of the frame, I think it needs some padding
2. would it be possible to show the header text somehow when the viewport is smaller?  it is a nice introduction to the page’s content
3. On the features page, I think it would be pretty easy to miss the link to the page on time travel debugging if the page is small and the sidebar isn’t shown, maybe we could include that in the page introduction

**Comment by bhackett1024** [comment]
These are fixed now
