### ISSUE TITLE
Fix arrow between pages

### ISSUE THREAD

**Issue by bhackett1024** [WebReplay/webreplay-website#9]
The arrow icon at the bottom of perfect-bug-reports.html isn't rendering properly on either desktop or mobile.

**Comment by jasonLaster** [comment]
I think it is fixed now

**Comment by bhackett1024** [comment]
The problem here is that the charset was not being sent in documents, causing the browser to render things either correctly or incorrectly, depending on which server is used and the other metadata it sent.
